{
  config,
  pkgs,
  lib,
  ...
}: let
  torrentsDir = "/home/d7tun6/files/mounts/wd-purple/files/torrents";
in {
  # uid 1000 = d7tun6, gid 100 = users (keep-id maps container PUID/PGID to these)
  systemd.tmpfiles.rules = [
    "d ${torrentsDir}/bittorrent-config 0755 1000 100 -"
    "d ${torrentsDir}/downloads         0755 1000 100 -"
    "d ${torrentsDir}/qbitwebui-data   0755 1000 100 -"
  ];

  virtualisation.oci-containers = {
    backend = "podman";
    containers = {
      qbittorrent = {
        image = "linuxserver/qbittorrent:latest";
        podman.user = "d7tun6";
        ports = [
          "18080:8080"
          "6881:6881"
          "6881:6881/udp"
          "9876:9876"
        ];
        volumes = [
          "${torrentsDir}/bittorrent-config:/config"
          "${torrentsDir}/downloads:/downloads"
        ];
        environment = {
          PUID = "1000";
          PGID = "100";
          TZ = "Asia/Yekaterinburg";
          WEBUI_PORT = "8080";
        };
        extraOptions = ["--network=podman"];
      };

      net-agent = {
        image = "ghcr.io/mkbula/qbitwebui-agent:latest";
        podman.user = "d7tun6";
        environment = {QBT_URL = "http://qbittorrent:8080";};
        dependsOn = ["qbittorrent"];
        extraOptions = ["--network=podman"];
      };

      qbitwebui = {
        image = "ghcr.io/mkbula/qbitwebui:latest";
        podman.user = "d7tun6";
        ports = ["3010:3000"];
        volumes = [
          "${torrentsDir}/qbitwebui-data:/data"
          "${torrentsDir}/downloads:/downloads:ro"
        ];
        environment = {
          DOWNLOADS_PATH = "/downloads";
        };
        dependsOn = ["qbittorrent"];
        extraOptions = [
          "--network=podman"
          "--env-file=/run/secrets/qbitwebui-encryption-key"
        ];
      };
    };
  };

  # Resource limits are merged into the units generated by oci-containers
  # (podman-<name>.service); the units themselves are NOT redeclared.
  systemd.services."podman-qbittorrent" = {
    unitConfig.RequiresMountsFor = ["/home/d7tun6/files/mounts/wd-purple"];
    serviceConfig = {
      ExecStartPre = lib.mkBefore [
        ''${config.virtualisation.podman.package}/bin/podman rm -f net-agent qbitwebui 2>/dev/null || true''
      ];
      CPUWeight = 20;
      MemoryMax = "3G";
      IOWeight = 20;
      KillMode = "mixed";
    };
  };
  systemd.services."podman-net-agent" = {
    partOf = ["podman-qbittorrent.service"];
    serviceConfig = {
      CPUWeight = 20;
      MemoryMax = "3G";
      IOWeight = 20;
      KillMode = "mixed";
    };
  };
  systemd.services."podman-qbitwebui" = {
    after = ["sops-install-secrets.service"];
    requires = ["sops-install-secrets.service"];
    partOf = ["podman-qbittorrent.service"];
    serviceConfig = {
      CPUWeight = 20;
      MemoryMax = "3G";
      IOWeight = 20;
      KillMode = "mixed";
    };
  };
}
